# Profile information
name: Shane Quick
title: Shane Quick
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site dedicated to showcasing the projects of Shane Quick. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shanesfast.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
githubrepo: shanesfast
linkedin: shane-quick

# Contact form
email: shanesfast@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
sass:
    sass_dir: _sass
    load_paths:
        - _sass
        - _sass/_main
        - _sass/_normalize
        - _sass/_syntax

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]

# Fixes Github Metadata warning on Jekyll server builds
github: [metadata]
