# Profile information
name: Taylor Lewis
title: Phay Photography
description: > # this means to ignore newlines until "baseurl:"
  This is an example site for Taylor!
permalink: ':title/'
baseurl: "/phayphotos" # the subpath of your site, e.g. /blog
url: "https://shanesfast.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: https://www.facebook.com/tayphay01 #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: shanesfast@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
sass:
    sass_dir: _sass
    load_paths:
        - _sass
        - _sass/_main
        - _sass/_normalize
        - _sass/_syntax

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
